// Auto-generated by generate-igloo-layouts.ts
// Generated: 2026-06-13T09:43:58.916Z
// Regenerate: npx tsx scripts/generate-igloo-layouts.ts

export type LayerType = "floor" | "bg" | "fg";

export type SceneLayer = {
	frameName: string;
	x: number;
	y: number;
	originX: number;
	originY: number;
	layerType: LayerType;
	flipX?: true;
};

export type SceneLayout = {
	floorFrame: number;
	layers: SceneLayer[];
};

export const SCENE_LAYOUTS: Record<number, SceneLayout> = {
	"0": {
		"floorFrame": 17,
		"layers": [
			{
				"frameName": "floor-1",
				"x": 760,
				"y": 624,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "floor-2",
				"x": 760,
				"y": 624,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "floor_4",
				"x": 760,
				"y": 624,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			}
		]
	},
	"1": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "floor",
				"x": 765,
				"y": 639,
				"originX": 0.5006337135614702,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall_1",
				"x": 570,
				"y": 378,
				"originX": 0.5010266940451745,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 972,
				"y": 388,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "chimney",
				"x": 887,
				"y": 120,
				"originX": 0.5050505050505051,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "window",
				"x": 828,
				"y": 476,
				"originX": 0.5014164305949008,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 491,
				"y": 467,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"2": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "floor",
				"x": 765,
				"y": 639,
				"originX": 0.5006337135614702,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall_1",
				"x": 570,
				"y": 378,
				"originX": 0.5010266940451745,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 972,
				"y": 388,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "chimney",
				"x": 887,
				"y": 120,
				"originX": 0.5050505050505051,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "window",
				"x": 828,
				"y": 476,
				"originX": 0.5014164305949008,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 491,
				"y": 467,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"3": {
		"floorFrame": 2,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 636,
				"originX": 0.5003940110323088,
				"originY": 0.5013477088948787,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 243,
				"y": 478,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_1",
				"x": 321,
				"y": 389,
				"originX": 0.5010266940451745,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 762,
				"y": 295,
				"originX": 0.5008695652173913,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_3",
				"x": 1210,
				"y": 401,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "window",
				"x": 1072,
				"y": 485,
				"originX": 0.5014164305949008,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "window",
				"x": 529,
				"y": 481,
				"originX": 0.5014164305949008,
				"originY": 0.5,
				"layerType": "bg",
				"flipX": true
			},
			{
				"frameName": "chimney",
				"x": 1127,
				"y": 133,
				"originX": 0.5050505050505051,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"4": {
		"floorFrame": 2,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 636,
				"originX": 0.5003940110323088,
				"originY": 0.5013477088948787,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 243,
				"y": 478,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_1",
				"x": 321,
				"y": 389,
				"originX": 0.5010266940451745,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 762,
				"y": 295,
				"originX": 0.5008695652173913,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_3",
				"x": 1210,
				"y": 401,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "window",
				"x": 1072,
				"y": 485,
				"originX": 0.5014164305949008,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "window",
				"x": 529,
				"y": 481,
				"originX": 0.5014164305949008,
				"originY": 0.5,
				"layerType": "bg",
				"flipX": true
			},
			{
				"frameName": "chimney",
				"x": 1127,
				"y": 133,
				"originX": 0.5050505050505051,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"5": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "floor",
				"x": 765,
				"y": 639,
				"originX": 0.5006337135614702,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall_1",
				"x": 570,
				"y": 378,
				"originX": 0.5010266940451745,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 972,
				"y": 388,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 491,
				"y": 467,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"6": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "floor",
				"x": 765,
				"y": 639,
				"originX": 0.5006337135614702,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall_1",
				"x": 570,
				"y": 378,
				"originX": 0.5010266940451745,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 972,
				"y": 388,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 491,
				"y": 467,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"8": {
		"floorFrame": 2,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 636,
				"originX": 0.5003940110323088,
				"originY": 0.5013477088948787,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 243,
				"y": 478,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_1",
				"x": 321,
				"y": 389,
				"originX": 0.5010266940451745,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 762,
				"y": 295,
				"originX": 0.5008695652173913,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_3",
				"x": 1210,
				"y": 401,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"9": {
		"floorFrame": 2,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 636,
				"originX": 0.5003940110323088,
				"originY": 0.5013477088948787,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 243,
				"y": 478,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_1",
				"x": 321,
				"y": 389,
				"originX": 0.5010266940451745,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 762,
				"y": 295,
				"originX": 0.5008695652173913,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_3",
				"x": 1210,
				"y": 401,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"10": {
		"floorFrame": 4,
		"layers": [
			{
				"frameName": "floor",
				"x": 769,
				"y": 691,
				"originX": 0.5004468275245755,
				"originY": 0.5017421602787456,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 424,
				"y": 474,
				"originX": 0.5054945054945055,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall",
				"x": 760,
				"y": 402,
				"originX": 0.5004101722723544,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"11": {
		"floorFrame": 5,
		"layers": [
			{
				"frameName": "floor_1",
				"x": 760,
				"y": 703,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "floor_2",
				"x": 748,
				"y": 838,
				"originX": 0.5,
				"originY": 0.5070422535211268,
				"layerType": "floor"
			},
			{
				"frameName": "wall",
				"x": 760,
				"y": 426,
				"originX": 0.5003441156228493,
				"originY": 0.5006896551724138,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 421,
				"y": 555,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"12": {
		"floorFrame": 6,
		"layers": [
			{
				"frameName": "wood",
				"x": 1342,
				"y": 742,
				"originX": 0.5084745762711864,
				"originY": 0.5185185185185185,
				"layerType": "floor",
				"flipX": true
			},
			{
				"frameName": "wood",
				"x": 177,
				"y": 742,
				"originX": 0.5084745762711864,
				"originY": 0.5185185185185185,
				"layerType": "floor"
			},
			{
				"frameName": "floor",
				"x": 760,
				"y": 753,
				"originX": 0.5004095004095004,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall",
				"x": 760,
				"y": 400,
				"originX": 0.5003903200624512,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 339,
				"y": 571,
				"originX": 0.5084745762711864,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"13": {
		"floorFrame": 3,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 630,
				"originX": 0.5003861003861004,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "stairs_top",
				"x": 763,
				"y": 667,
				"originX": 0.5,
				"originY": 0.5035971223021583,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 235,
				"y": 556,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_1",
				"x": 757,
				"y": 380,
				"originX": 0.5003615328994938,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "stairs",
				"x": 777,
				"y": 667,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 925,
				"y": 811,
				"originX": 0.5,
				"originY": 0.5015197568389058,
				"layerType": "bg"
			}
		]
	},
	"14": {
		"floorFrame": 3,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 630,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 235,
				"y": 556,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg",
				"x": 757,
				"y": 380,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "step",
				"x": 777,
				"y": 667,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg_wall",
				"x": 925,
				"y": 811,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"15": {
		"floorFrame": 7,
		"layers": [
			{
				"frameName": "igloo",
				"x": 766,
				"y": 467,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 764,
				"y": 757,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"16": {
		"floorFrame": 8,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 414,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 758,
				"y": 516,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"17": {
		"floorFrame": 3,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 630,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 235,
				"y": 556,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_1",
				"x": 757,
				"y": 380,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "step",
				"x": 777,
				"y": 667,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_2",
				"x": 925,
				"y": 811,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"18": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 530,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 922.1773064411411,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"19": {
		"floorFrame": 10,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 746,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "walls",
				"x": 764,
				"y": 454,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "roof",
				"x": 746,
				"y": 452.5399877040221,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"20": {
		"floorFrame": 11,
		"layers": [
			{
				"frameName": "pumkin",
				"x": 754,
				"y": 456,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"21": {
		"floorFrame": 3,
		"layers": [
			{
				"frameName": "grass_floor",
				"x": 495,
				"y": 645,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "main_floor",
				"x": 936,
				"y": 622,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "stairs_top",
				"x": 785,
				"y": 674,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "walls",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 719,
				"y": 245,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "stairs",
				"x": 806,
				"y": 671,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bottomwall",
				"x": 957,
				"y": 817,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"22": {
		"floorFrame": 8,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 414,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 758,
				"y": 516,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"25": {
		"floorFrame": 11,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 551,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "floor",
				"x": 778,
				"y": 739,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "fg",
				"x": 755,
				"y": 237,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"26": {
		"floorFrame": 12,
		"layers": [
			{
				"frameName": "floor",
				"x": 768,
				"y": 691,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "walls",
				"x": 760,
				"y": 445.5,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door0001",
				"x": 279,
				"y": 550,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"27": {
		"floorFrame": 7,
		"layers": [
			{
				"frameName": "shadow",
				"x": 741,
				"y": 800,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "floor",
				"x": 768,
				"y": 658.7161529987027,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "walls",
				"x": 766,
				"y": 418,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "outline",
				"x": 758,
				"y": 524,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 782.5713063283397,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"29": {
		"floorFrame": 10,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 746,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "walls",
				"x": 764,
				"y": 454,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "roof",
				"x": 746,
				"y": 455.0588059548935,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"30": {
		"floorFrame": 3,
		"layers": [
			{
				"frameName": "snow",
				"x": 495,
				"y": 656,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "floor_1",
				"x": 936,
				"y": 622,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "stairs_top",
				"x": 785,
				"y": 674,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "walls",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 719,
				"y": 245,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "stairs",
				"x": 806,
				"y": 671,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "smallwall",
				"x": 957,
				"y": 817,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"32": {
		"floorFrame": 3,
		"layers": [
			{
				"frameName": "grass_floor",
				"x": 495,
				"y": 645,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "main_floor",
				"x": 936,
				"y": 622,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "stairs_top",
				"x": 793,
				"y": 677,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "walls",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door0001",
				"x": 719,
				"y": 245,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "stairs",
				"x": 811,
				"y": 674,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bottomwall",
				"x": 957,
				"y": 817,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"33": {
		"floorFrame": 8,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 414,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 758,
				"y": 516,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"35": {
		"floorFrame": 13,
		"layers": [
			{
				"frameName": "floor",
				"x": 570,
				"y": 587,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 210,
				"y": 317,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"36": {
		"floorFrame": 11,
		"layers": [
			{
				"frameName": "bg",
				"x": 754,
				"y": 374,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 305,
				"y": 643,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"37": {
		"floorFrame": 2,
		"layers": [
			{
				"frameName": "floor",
				"x": 745,
				"y": 655,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "bg",
				"x": 760,
				"y": 462,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 820,
				"y": 772.0955864181752,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			},
			{
				"frameName": "fg_hall",
				"x": 346,
				"y": 672.0738222536892,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"38": {
		"floorFrame": 8,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 414,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 758,
				"y": 516,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"39": {
		"floorFrame": 8,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 754,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "bg",
				"x": 760,
				"y": 334,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 759,
				"y": 581,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "frame",
				"x": 760,
				"y": 640,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"42": {
		"floorFrame": 14,
		"layers": [
			{
				"frameName": "chimneys",
				"x": 814,
				"y": 182,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "floor",
				"x": 740,
				"y": 481,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "background",
				"x": 894,
				"y": 455,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "paths",
				"x": 716,
				"y": 625,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "castle",
				"x": 726,
				"y": 301,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "castlebush",
				"x": 723,
				"y": 449,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "cabin",
				"x": 259,
				"y": 403,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "sidewalk",
				"x": 640,
				"y": 844,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "snowpile",
				"x": 760,
				"y": 751,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "cabinbush",
				"x": 85,
				"y": 613,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "igloo",
				"x": 1234,
				"y": 411,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "igloobush",
				"x": 1398,
				"y": 553,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "exit",
				"x": 146,
				"y": 694,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"43": {
		"floorFrame": 11,
		"layers": [
			{
				"frameName": "floor",
				"x": 781,
				"y": 719,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "igloo",
				"x": 752,
				"y": 571,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 772,
				"y": 473,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"49": {
		"floorFrame": 15,
		"layers": [
			{
				"frameName": "background",
				"x": 760,
				"y": 360.64031301839026,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "foreground",
				"x": 760,
				"y": 963.7091586327042,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"50": {
		"floorFrame": 15,
		"layers": [
			{
				"frameName": "bg-lower",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg_upper",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 964.9881605335881,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"51": {
		"floorFrame": 18,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg-upper",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 980.486100501291,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"52": {
		"floorFrame": 6,
		"layers": [
			{
				"frameName": "bg-lower",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg-upper",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"53": {
		"floorFrame": 15,
		"layers": [
			{
				"frameName": "bg-lower",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg-upper",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 962.1435010445438,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"55": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 970.3177007592319,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"56": {
		"floorFrame": 4,
		"layers": [
			{
				"frameName": "bg-lower",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 369.69045232017226,
				"y": 672.6479067928531,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg-upper",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 963.3509157454945,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"57": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 964.9881605335881,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"58": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 965.9602341346081,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"63": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "bg-lower",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg-middle",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 229,
				"y": 330.95607374795964,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg-upper",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "water-anim-lower0001",
				"x": 1367,
				"y": 661,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "water-anim-upper0001",
				"x": 1334,
				"y": 340,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 980.0929316408556,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"65": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 999.630172000273,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"67": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "bg_lower",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 215.72656106823746,
				"y": 625.4397284611821,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg-upper",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 975.6472409848757,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"68": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "bg-lower",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 213.32162953120633,
				"y": 533.8495897445486,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg-upper",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 962.2032731464072,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"69": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 980.9767912736692,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"75": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 980.5598978210556,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"76": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "bg-lower",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 124.60876175959251,
				"y": 704.1420696882822,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg-upper",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 1011.7065039428029,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"84": {
		"floorFrame": 15,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 966.8674310998953,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"90": {
		"floorFrame": 15,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 967.6529306464103,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"91": {
		"floorFrame": 15,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 1000.9141046033844,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"92": {
		"floorFrame": 15,
		"layers": [
			{
				"frameName": "bg",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 760,
				"y": 963.4627637495464,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"94": {
		"floorFrame": 15,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "fg",
				"x": 814,
				"y": 987,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"100": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "floormain",
				"x": 384,
				"y": 509,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "floor",
				"x": 5,
				"y": 10,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "floorpt2",
				"x": 5,
				"y": 10,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bg",
				"x": 5,
				"y": 10,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fan0001",
				"x": 760,
				"y": 109,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 484,
				"y": 457,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "button",
				"x": 944,
				"y": 432,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"101": {
		"floorFrame": 10,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 746,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "walls",
				"x": 764,
				"y": 454,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "roof",
				"x": 746,
				"y": 452.6268126095067,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"103": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "floor",
				"x": 759.9999992070846,
				"y": 679,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "right",
				"x": 1082,
				"y": 494,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "rightholder",
				"x": 1228,
				"y": 509,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fireback",
				"x": 768,
				"y": 532,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "firepit",
				"x": 769,
				"y": 575,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fire_0001",
				"x": 767,
				"y": 544,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fireholder",
				"x": 770,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "stairs",
				"x": 486,
				"y": 498,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "platform",
				"x": 891,
				"y": 410,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 301,
				"y": 387,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"104": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "doorholderback",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 1102,
				"y": 486,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "two_row_box",
				"x": 334.08063896404184,
				"y": 598.0095044908546,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "doorholder",
				"x": 1157.687846758355,
				"y": 597.9952951920394,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 766.9897725660235,
				"y": 731.6318123768418,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			}
		]
	},
	"105": {
		"floorFrame": 12,
		"layers": [
			{
				"frameName": "watchtower",
				"x": 774,
				"y": 459,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "steps",
				"x": 742,
				"y": 771.5175842920186,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"106": {
		"floorFrame": 18,
		"layers": [
			{
				"frameName": "floor",
				"x": 742,
				"y": 559,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 232.24166339180516,
				"y": 622.0082383623496,
				"originX": 0.5203787581073197,
				"originY": 0.8155739726327652,
				"layerType": "bg"
			},
			{
				"frameName": "wall",
				"x": 742,
				"y": 421,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"107": {
		"floorFrame": 3,
		"layers": [
			{
				"frameName": "grass_floor",
				"x": 495,
				"y": 645,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "main_floor",
				"x": 936,
				"y": 602,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "stairs_top",
				"x": 785,
				"y": 674,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "walls",
				"x": 759.5,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 719,
				"y": 245,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "stairs",
				"x": 806,
				"y": 671,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bottomwall",
				"x": 957,
				"y": 817,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"109": {
		"floorFrame": 2,
		"layers": [
			{
				"frameName": "floor",
				"x": 757.5,
				"y": 655,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 267,
				"y": 555.4592934004506,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall",
				"x": 755,
				"y": 371,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "window_L",
				"x": 546.5,
				"y": 497.5,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "window_R",
				"x": 965.5,
				"y": 497,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"110": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "sideladder",
				"x": 1328,
				"y": 630,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "floor",
				"x": 701,
				"y": 598,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall",
				"x": 705,
				"y": 380,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall_shelf",
				"x": 1214,
				"y": 192,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "doorframe",
				"x": 1239,
				"y": 510,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door",
				"x": 1230.400830697391,
				"y": 553.0236897342318,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "shelf",
				"x": 695,
				"y": 732,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "fg",
				"x": 720.731210119527,
				"y": 880.2480417645054,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "fg"
			},
			{
				"frameName": "windowlight",
				"x": 734,
				"y": 596,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"111": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "floor",
				"x": 765,
				"y": 664,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "bg",
				"x": 760,
				"y": 394,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"112": {
		"floorFrame": 18,
		"layers": [
			{
				"frameName": "floor",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "building",
				"x": 760,
				"y": 480,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "door0001",
				"x": 764.2035030092359,
				"y": 331.534778333502,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bow",
				"x": 733,
				"y": 183,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_holder",
				"x": 192.22574428511476,
				"y": 472.6138357232787,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_holder",
				"x": 1327.775,
				"y": 489.71878322432786,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "cherries",
				"x": 771.0021328904963,
				"y": 561.1706312397099,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bow_left",
				"x": 592,
				"y": 118,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bow_right",
				"x": 928,
				"y": 118,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_left_rail",
				"x": 345.5808563782359,
				"y": 599.2596905823859,
				"originX": 0.34677529363664544,
				"originY": 0.6120729280829108,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_top_right_handle",
				"x": 650,
				"y": 488.0929337068483,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair",
				"x": 458,
				"y": 657,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_right_rail",
				"x": 536.361901273333,
				"y": 625.109406092479,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_right_handle",
				"x": 591.4598303121369,
				"y": 749.6495757803422,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_left_handle",
				"x": 294,
				"y": 755,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_top_left_handle",
				"x": 479.6900602031763,
				"y": 459.56144487623106,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_left_rail",
				"x": 1116,
				"y": 595,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_top_right_handle",
				"x": 876,
				"y": 486,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair",
				"x": 1064,
				"y": 654,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_left_handle",
				"x": 1231,
				"y": 751,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_top_left_handle",
				"x": 1050,
				"y": 455,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_right_rail",
				"x": 888,
				"y": 623,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "left_stair_right_handle",
				"x": 966,
				"y": 745,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"113": {
		"floorFrame": 7,
		"layers": [
			{
				"frameName": "floor",
				"x": 769,
				"y": 464,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "igloo",
				"x": 769,
				"y": 466,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "foreground",
				"x": 194,
				"y": 392.0977952753993,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"114": {
		"floorFrame": 18,
		"layers": [
			{
				"frameName": "floor",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "river",
				"x": 699,
				"y": 731,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "lavafalls0001",
				"x": 783.9955030487847,
				"y": 166.1594512196758,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "rock",
				"x": 735,
				"y": 500,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"115": {
		"floorFrame": 18,
		"layers": [
			{
				"frameName": "floor",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "wall",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "watertop0001",
				"x": 619,
				"y": 137,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "topwater0001",
				"x": 529.5,
				"y": 213.5,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bubblestop0001",
				"x": 558,
				"y": 334.5,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bubblesmidone0001",
				"x": 670,
				"y": 572.5,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bubblesmidtwo0001",
				"x": 883.5,
				"y": 514.5,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "bottomwater0001",
				"x": 1170,
				"y": 922.5,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "waterbottom0001",
				"x": 1323,
				"y": 894,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"116": {
		"floorFrame": 16,
		"layers": [
			{
				"frameName": "floor",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "door0001",
				"x": 258.86543553995364,
				"y": 422.2110801404175,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "rail",
				"x": 1088,
				"y": 461,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "rink",
				"x": 1083,
				"y": 585,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "lamp",
				"x": 1046,
				"y": 187,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	},
	"117": {
		"floorFrame": 1,
		"layers": [
			{
				"frameName": "railroad",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "floor",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "floor"
			},
			{
				"frameName": "door",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			},
			{
				"frameName": "wall",
				"x": 0,
				"y": 0,
				"originX": 0.5,
				"originY": 0.5,
				"layerType": "bg"
			}
		]
	}
};

export const FLOOR_FRAME_MAP: Record<number, number> = {
	"0": 17,
	"1": 1,
	"2": 1,
	"3": 2,
	"4": 2,
	"5": 1,
	"6": 1,
	"8": 2,
	"9": 2,
	"10": 4,
	"11": 5,
	"12": 6,
	"13": 3,
	"14": 3,
	"15": 7,
	"16": 8,
	"17": 3,
	"18": 1,
	"19": 10,
	"20": 11,
	"21": 3,
	"22": 8,
	"23": 7,
	"24": 11,
	"25": 11,
	"26": 12,
	"27": 7,
	"28": 12,
	"29": 10,
	"30": 3,
	"32": 3,
	"33": 8,
	"35": 13,
	"36": 11,
	"37": 2,
	"38": 8,
	"39": 8,
	"40": 14,
	"41": 15,
	"42": 14,
	"43": 11,
	"49": 15,
	"50": 15,
	"51": 18,
	"52": 6,
	"53": 15,
	"55": 16,
	"56": 4,
	"57": 16,
	"58": 16,
	"63": 16,
	"65": 16,
	"67": 16,
	"68": 16,
	"69": 16,
	"75": 16,
	"76": 1,
	"84": 15,
	"85": 15,
	"86": 15,
	"87": 15,
	"88": 15,
	"89": 15,
	"90": 15,
	"91": 15,
	"92": 15,
	"93": 15,
	"94": 15,
	"98": 15,
	"99": 1,
	"100": 1,
	"101": 10,
	"103": 16,
	"104": 16,
	"105": 12,
	"106": 18,
	"107": 3,
	"108": 3,
	"109": 2,
	"110": 1,
	"111": 1,
	"112": 18,
	"113": 7,
	"114": 18,
	"115": 18,
	"116": 16,
	"117": 1
};
